disabled_rules:
  - trailing_whitespace
  - orphaned_doc_comment
  - nesting

opt_in_rules:
  - let_var_whitespace
  - force_unwrapping

included:
  - Danggn
excluded:
  # AppDelegate, SceneDelegate file 무시
  - Danggn/AppDelegate.swift
  - Danggn/SceneDelegate.swift

force_cast: error
force_unwrapping: error
